// Control-plane messages exchanged over the tunnel (Decision #18).
// The handshake (Hello/HelloAck) runs on the raw TLS connection before
// multiplexing starts; StreamHeader opens every data stream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamKind int32

const (
	StreamKind_STREAM_KIND_UNSPECIFIED StreamKind = 0
	StreamKind_STREAM_KIND_CONTROL     StreamKind = 1
	StreamKind_STREAM_KIND_DATA        StreamKind = 2
)

// Enum value maps for StreamKind.
var (
	StreamKind_name = map[int32]string{
		0: "STREAM_KIND_UNSPECIFIED",
		1: "STREAM_KIND_CONTROL",
		2: "STREAM_KIND_DATA",
	}
	StreamKind_value = map[string]int32{
		"STREAM_KIND_UNSPECIFIED": 0,
		"STREAM_KIND_CONTROL":     1,
		"STREAM_KIND_DATA":        2,
	}
)

func (x StreamKind) Enum() *StreamKind {
	p := new(StreamKind)
	*p = x
	return p
}

func (x StreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_proto_enumTypes[0].Descriptor()
}

func (StreamKind) Type() protoreflect.EnumType {
	return &file_api_control_proto_enumTypes[0]
}

func (x StreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamKind.Descriptor instead.
func (StreamKind) EnumDescriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

// Hello is the agent's opening message: authenticate and advertise the
// services this agent can reach locally.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version guards against incompatible peers; bump on any
	// breaking change to these messages or the framing.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentName       string `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Token           string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// services the agent advertises, by name (targets stay agent-local).
	Services      []string `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// HelloAck accepts or rejects the agent. On rejection the server closes
// the connection immediately after writing this.
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HelloAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StreamHeader is written by the server as the first frame on every
// stream, telling the agent what kind of a stream it is
type StreamHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Kind          StreamKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=krtica.v1.StreamKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	mi := &file_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *StreamHeader) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StreamHeader) GetKind() StreamKind {
	if x != nil {
		return x.Kind
	}
	return StreamKind_STREAM_KIND_UNSPECIFIED
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_api_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_api_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_api_control_proto protoreflect.FileDescriptor

const file_api_control_proto_rawDesc = "" +
	"\n" +
	"\x11api/control.proto\x12\tkrtica.v1\"\x83\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\"0\n" +
	"\bHelloAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\fStreamHeader\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.krtica.v1.StreamKindR\x04kind\"\"\n" +
	"\x04Ping\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\"\n" +
	"\x04Pong\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence*X\n" +
	"\n" +
	"StreamKind\x12\x1b\n" +
	"\x17STREAM_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STREAM_KIND_CONTROL\x10\x01\x12\x14\n" +
	"\x10STREAM_KIND_DATA\x10\x02B0Z.github.com/urosevicvuk/krtica/internal/wire/pbb\x06proto3"

var (
	file_api_control_proto_rawDescOnce sync.Once
	file_api_control_proto_rawDescData []byte
)

func file_api_control_proto_rawDescGZIP() []byte {
	file_api_control_proto_rawDescOnce.Do(func() {
		file_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)))
	})
	return file_api_control_proto_rawDescData
}

var file_api_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_control_proto_goTypes = []any{
	(StreamKind)(0),      // 0: krtica.v1.StreamKind
	(*Hello)(nil),        // 1: krtica.v1.Hello
	(*HelloAck)(nil),     // 2: krtica.v1.HelloAck
	(*StreamHeader)(nil), // 3: krtica.v1.StreamHeader
	(*Ping)(nil),         // 4: krtica.v1.Ping
	(*Pong)(nil),         // 5: krtica.v1.Pong
}
var file_api_control_proto_depIdxs = []int32{
	0, // 0: krtica.v1.StreamHeader.kind:type_name -> krtica.v1.StreamKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_control_proto_init() }
func file_api_control_proto_init() {
	if File_api_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_control_proto_goTypes,
		DependencyIndexes: file_api_control_proto_depIdxs,
		EnumInfos:         file_api_control_proto_enumTypes,
		MessageInfos:      file_api_control_proto_msgTypes,
	}.Build()
	File_api_control_proto = out.File
	file_api_control_proto_goTypes = nil
	file_api_control_proto_depIdxs = nil
}
